'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property FacultyLimit() As Integer
            Get
                Return CType(Me("FacultyLimit"),Integer)
            End Get
            Set
                Me("FacultyLimit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ShowTimes() As Boolean
            Get
                Return CType(Me("ShowTimes"),Boolean)
            End Get
            Set
                Me("ShowTimes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UseOpenFile() As Boolean
            Get
                Return CType(Me("UseOpenFile"),Boolean)
            End Get
            Set
                Me("UseOpenFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Courses|YCCC")>  _
        Public Property ScheduleTab() As String
            Get
                Return CType(Me("ScheduleTab"),String)
            End Get
            Set
                Me("ScheduleTab") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sequences")>  _
        Public Property SequenceTab() As String
            Get
                Return CType(Me("SequenceTab"),String)
            End Get
            Set
                Me("SequenceTab") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ShowSequenceWarnings() As Boolean
            Get
                Return CType(Me("ShowSequenceWarnings"),Boolean)
            End Get
            Set
                Me("ShowSequenceWarnings") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Rooms")>  _
        Public Property capabilitiesTab() As String
            Get
                Return CType(Me("capabilitiesTab"),String)
            End Get
            Set
                Me("capabilitiesTab") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property DefaultRoomSize() As Integer
            Get
                Return CType(Me("DefaultRoomSize"),Integer)
            End Get
            Set
                Me("DefaultRoomSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Max Capacity|Cap")>  _
        Public Property MaxCapacityColumn() As String
            Get
                Return CType(Me("MaxCapacityColumn"),String)
            End Get
            Set
                Me("MaxCapacityColumn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Capabilities")>  _
        Public Property RoomCapabilityColumn() As String
            Get
                Return CType(Me("RoomCapabilityColumn"),String)
            End Get
            Set
                Me("RoomCapabilityColumn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("*course*number*|*number*course*")>  _
        Public Property CourseNumColumn() As String
            Get
                Return CType(Me("CourseNumColumn"),String)
            End Get
            Set
                Me("CourseNumColumn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("*instructor*")>  _
        Public Property InstructorCol() As String
            Get
                Return CType(Me("InstructorCol"),String)
            End Get
            Set
                Me("InstructorCol") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("*days*")>  _
        Public Property DaysCol() As String
            Get
                Return CType(Me("DaysCol"),String)
            End Get
            Set
                Me("DaysCol") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("*time*")>  _
        Public Property TimeCol() As String
            Get
                Return CType(Me("TimeCol"),String)
            End Get
            Set
                Me("TimeCol") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("room")>  _
        Public Property RoomCol() As String
            Get
                Return CType(Me("RoomCol"),String)
            End Get
            Set
                Me("RoomCol") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Enr")>  _
        Public Property MaxEnroll() As String
            Get
                Return CType(Me("MaxEnroll"),String)
            End Get
            Set
                Me("MaxEnroll") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Cur")>  _
        Public Property CurEnroll() As String
            Get
                Return CType(Me("CurEnroll"),String)
            End Get
            Set
                Me("CurEnroll") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EnrollTypeIsCurEnroll() As Boolean
            Get
                Return CType(Me("EnrollTypeIsCurEnroll"),Boolean)
            End Get
            Set
                Me("EnrollTypeIsCurEnroll") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LastFullSearchOption() As Boolean
            Get
                Return CType(Me("LastFullSearchOption"),Boolean)
            End Get
            Set
                Me("LastFullSearchOption") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property lastSemestersChecked() As String
            Get
                Return CType(Me("lastSemestersChecked"),String)
            End Get
            Set
                Me("lastSemestersChecked") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Description")>  _
        Public Property roomDescription() As String
            Get
                Return CType(Me("roomDescription"),String)
            End Get
            Set
                Me("roomDescription") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property includeInfoResults() As Boolean
            Get
                Return CType(Me("includeInfoResults"),Boolean)
            End Get
            Set
                Me("includeInfoResults") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Notes")>  _
        Public Property notesCol() As String
            Get
                Return CType(Me("notesCol"),String)
            End Get
            Set
                Me("notesCol") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Contact*|Credit*")>  _
        Public Property contactHoursCol() As String
            Get
                Return CType(Me("contactHoursCol"),String)
            End Get
            Set
                Me("contactHoursCol") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property checkContactHours() As Boolean
            Get
                Return CType(Me("checkContactHours"),Boolean)
            End Get
            Set
                Me("checkContactHours") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property allowGhosts() As Boolean
            Get
                Return CType(Me("allowGhosts"),Boolean)
            End Get
            Set
                Me("allowGhosts") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ScheduleAnalyzer.My.MySettings
            Get
                Return Global.ScheduleAnalyzer.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
